= Primes Multiplication Table

== Overview

This project is the solution to the Funding Circle Coding Challenge.  The goal is to
produce a multiplication table for the first 10 prime numbers, formatted nicely to stdout.
The program is to be run from the command line.

This solution is written in Clojure, and assumes you have a current version of Leiningen
(2.3+) installed.  It is also assumed a current version of Java (1.8) and Clojure (1.6)
are properly configured on your system.

If everything is configured correctly, you should be able to see results like the
following:
----
~/work/prime > lein --version
Leiningen 2.4.3 on Java 1.8.0_11 Java HotSpot(TM) 64-Bit Server VM
~/work/prime > lein run

             2      3      5      7     11     13     17     19     23     29
      2      4      6     10     14     22     26     34     38     46     58
      3      6      9     15     21     33     39     51     57     69     87
      5     10     15     25     35     55     65     85     95    115    145
      7     14     21     35     49     77     91    119    133    161    203
     11     22     33     55     77    121    143    187    209    253    319
     13     26     39     65     91    143    169    221    247    299    377
     17     34     51     85    119    187    221    289    323    391    493
     19     38     57     95    133    209    247    323    361    437    551
     23     46     69    115    161    253    299    391    437    529    667
     29     58     87    145    203    319    377    493    551    667    841
----

== Invocation Options

The program accepts an optional size parameter in the interval [1..25] as such:
----
~/work/prime > lein run 5
size: 5

             2      3      5      7     11
      2      4      6     10     14     22
      3      6      9     15     21     33
      5     10     15     25     35     55
      7     14     21     35     49     77
     11     22     33     55     77    121

~/work/prime > 
----

== Unit Tests

A number of unit tests were written to verify both correctness and performance of the
code.  The basic unit tests may be invoked by:
----
~/work/prime > lein test

lein test prime.prime-1-test

lein test prime.prime-2-test

lein test prime.prime-3-test

lein test prime.prime-4-test

lein test prime.util-test
 1 2 5 10 20 50 100 200 500 1000

Ran 7 tests containing 51 assertions.
0 failures, 0 errors.
~/work/prime > 
----

and the performance tests may be invoked by:
----
~/work/prime > lein test :perf

lein test prime.prime-1-test
WARNING: Final GC required 2.022539139339225 % of runtime
Evaluation count : 840 in 60 samples of 14 calls.
             Execution time mean : 69.712852 ms
    Execution time std-deviation : 444.883750 µs
   Execution time lower quantile : 68.995497 ms ( 2.5%)
   Execution time upper quantile : 70.462231 ms (97.5%)
                   Overhead used : 4.945325 ns
"Elapsed time: 96665.693204 msecs"

lein test prime.prime-2-test
Evaluation count : 2700 in 60 samples of 45 calls.
             Execution time mean : 22.374190 ms
    Execution time std-deviation : 232.116951 µs
   Execution time lower quantile : 22.092988 ms ( 2.5%)
   Execution time upper quantile : 22.869066 ms (97.5%)
                   Overhead used : 4.945325 ns

Found 5 outliers in 60 samples (8.3333 %)
        low-severe       4 (6.6667 %)
        low-mild         1 (1.6667 %)
 Variance from outliers : 1.6389 % Variance is slightly inflated by outliers
"Elapsed time: 80906.506081 msecs"

lein test prime.prime-3-test
Evaluation count : 2640 in 60 samples of 44 calls.
             Execution time mean : 23.348639 ms
    Execution time std-deviation : 145.775467 µs
   Execution time lower quantile : 23.125065 ms ( 2.5%)
   Execution time upper quantile : 23.626269 ms (97.5%)
                   Overhead used : 4.945325 ns
"Elapsed time: 85057.339828 msecs"

lein test prime.prime-4-test
Evaluation count : 2580 in 60 samples of 43 calls.
             Execution time mean : 23.678175 ms
    Execution time std-deviation : 148.183698 µs
   Execution time lower quantile : 23.450320 ms ( 2.5%)
   Execution time upper quantile : 23.999340 ms (97.5%)
                   Overhead used : 4.945325 ns
"Elapsed time: 87972.364135 msecs"

lein test prime.util-test
Evaluation count : 1380 in 60 samples of 23 calls.
             Execution time mean : 44.325352 ms
    Execution time std-deviation : 257.036212 µs
   Execution time lower quantile : 43.888324 ms ( 2.5%)
   Execution time upper quantile : 44.860092 ms (97.5%)
                   Overhead used : 4.945325 ns

Found 1 outliers in 60 samples (1.6667 %)
        low-severe       1 (1.6667 %)
 Variance from outliers : 1.6389 % Variance is slightly inflated by outliers
"Elapsed time: 82075.038326 msecs"

Ran 5 tests containing 0 assertions.
0 failures, 0 errors.
~/work/prime > 
----

One may also invoke all tests as:
----
~/work/prime > lein test :all
----

== Algorithms

Five different strategies for generating the prime numbers were investigated.  The
`prime.util` namespace contains a reference implementation using trial division.  The
namespaces `prime.prime-1` through `prime.prime-4` contain various implementations of the
sieve of Eratosthenes, modified to generate an arbitrary number of primes rather than all
primes below a given limit.

=== Reference Implementation - Trial Division

Namespace `prime.util` uses trial division in the function `is-prime-simple` to determine
if a given number is prime.  For a value N, it tests all possible divisors in the interval
[2..sqrt(N)] to see if any yield zero remainder.  If not, then N is prime.

This algorithm is very simple and does not exploit the fact that all primes after 2 are
odd.  However, it is meant to maximize simplicity rather than speed as it is a reference
implementation used to judge the correctness and speed of other, more complex algorithms.

The function `all-primes` returns an infinite lazy sequence of primes, while the function
`get-primes` returns a vector of the first N primes.  A helper function `all-prime?` is
available as an aid to testing correctness of other prime algorithms.

This algorithm requires an average of 44 ms to generate the first 1000 primes.

=== Sieve of Eratosthenes - Algorithm 1

Namespace `prime.prime-1` contains a simple version of the Sieve of Eratosthenes (SE). In it's
original design, the SE is designed to find all primes below a given value, which is
a different problem than finding the first N primes. Also, since SE makes extensive use of
memory for temporary storage, one must consider that DRAM access speed may slow the
algorithm and/or that memory exhaustion may occor.  For these reasons, we do not implement the
SE in its traditional form but use a loop-based version instead.

We seed the loop with the first prime value (2) and the next candidate prime (3).  The
loop uses the `is-prime` funciton to test each candidate, accumulating any primes found in
the `primes-so-far` array.  When enough primes have been found, the loop terminates.  Note
that only odd values after 2 are tested.

By using a loop, we do not require storage for non-primes like the pure SE algorithm.
Also, the loop can continue as long as required until `num-primes-desired` are found.  The
primary difference between the SE algorithm and simple trial division is that, for any
prime candidate value N, only primes less than N need be considered as possible divisors
(any non-prime integer must have smaller divisors which are prime).  As this is a baseline
algorithm, we do not restrict possible prime divisors as less than sqrt(N).

This algorithm requires an average of 70 ms to generate the first 1000 primes, about 1.6x
slower than `prime.util`.  Although the SE algorithm is more efficient in the long
run, we are not exploiting the sqrt(N) divisor limit which gives `prime.util` an
advantage.

=== Sieve of Eratosthenes - Algorithm 2

Namespace `prime.prime-2` contains an improved version of the SE algorithm, which does
include the sqrt(N) divisor limit, which is the only change compared to `prime.prime-1`.  

This algorithm requires an average of 22 ms to generate the first 1000 primes, about 2x
faster than `prime.util`.  Note that this is not as efficient as possible, since the
primes are filtered below sqrt(N) on each call to `is-prime`, which represents repeated
work that could be eliminated by a more complicated version of the algorithm.

=== Sieve of Eratosthenes - Algorithm 3

Namespace `prime.prime-3` is a modified version of `prime.prime-2', where the function
`is-prime` has been inlined into the loop to eliminate a function call.

This algorithm requires an average of 23 ms to generate the first 1000 primes, nearly
identical to `prime.prime-2` (many previous timings showed them to have identical
execution times). Eliminating the function call has had no measurable effect.

=== Sieve of Eratosthenes - Algorithm 4

Namespace `prime.prime-4` is a modified version of `prime.prime-2'. It adds a function
`all-primes` that returns an infinite lazy sequence of all primes [2 3 5 7 11...].

The (internal) function `all-primes*` does lion's share of the work, generating the lazy
sequence.  It calls itself recursively, generating another prime on each invocation.  The
function `all-primes` provides seed values to `all-primes*` and is the external interface.

This algorithm requires an average of 23 ms to generate the first 1000 primes, essentially
identical to `prime.prime-2`.  Returning the primes as an infinite lazy sequence has had no
measurable cost, but does support added flexibility for clients who wish to take advantage
of it.


== License

Copyright © 2014 Alan Thompson. 

Distributed under the Eclipse Public License, the same as Clojure.
